### Solução do Desafio da aula 3

#### Desafio 2

Use o dicionário de notas e retorne o nome dos alunos que irão ser aprovados, reprovados e os que vão ficar de recuperação!

# Qualquer coisa

In [37]:

notas_alunos = {"Bruno": 4.5, 
         "Mauricio": 8.7, 
         "Jéssica": 6.5,
         "Mariana": 7.4
        }

Lembrando: Aprovado para nota >=7 caso contrário, Recuperação para nota >=5 caso contrario Reprovado

### Solução 1

In [38]:
alunos_aprovados = []
alunos_reprovados = []
alunos_recuperacao = []
for i in notas_alunos.keys():
    if notas_alunos[i] >=7:
        alunos_aprovados.append(i)
    elif notas_alunos[i] >= 5:
        alunos_recuperacao.append(i)
    else:
        alunos_reprovados.append(i)

In [39]:
print(alunos_aprovados)
print(alunos_recuperacao)
print(alunos_reprovados)

['Mauricio', 'Mariana']
['Jéssica']
['Bruno']


### Solução 2

#### Usando lambda e filter
* Lambda: Funções lambda nada mais são do que funções anônimas. Enquanto funções normais podem ser criada utilizando def * * como prefixo, as funções lambda são criadas utilizando lambda.

* Vale notar que as funções lambda não utilizam a palavra reservada return pois o retorno dentro de lambda é implícito.

#### Entendendo como funcionam as funções Lambda

* 1. Definimos a função com a palavra lambda
* 2. Após definir a função os parâmetros devem ser inseridos
* 3. Colocamos : após os parâmetros
* 4. Inserimos a lógica da função


In [40]:
#Primeiro teste função lambda
funcao_teste = lambda a,b: a*b

#vou chamar a função passando os argumentos a e b
funcao_teste(2,3)


6

E o filter?
* Filter: Com o nome autoexplicativo, a função filter() filtra os elementos passados na função, de acordo com a função passada como primeiro argumento.

* sintaxe = filter(funcao_aplicada,lista_de_elementos)

### Aplicando no nosso problema

In [41]:
notas_alunos = {"Bruno": 4.5, 
         "Mauricio": 8.7, 
         "Jéssica": 6.5,
         "Mariana": 7.4
        }
alunos_aprovados = []

alunos_aprovados = list(filter(lambda x : notas_alunos[x] >= 7, notas_alunos.keys())) 

print(alunos_aprovados)

# lambda alimenta as chaves do dict e compara os valores no dict para cada chave,
#em relação aos critérios

['Mauricio', 'Mariana']


### Solução 3

### Usando List Comprehensions (Compreensão de Listas) - aqui no exemplo usamos Dic Comprehensions

* É uma forma concisa de criar e manipular listas

* sintaxe: [expr for item in lista] ou seja, aplique a expressão expr em cada item da lista

In [42]:
#Exemplo: aplique a potência de 2 em todos os itens da lista.
lista = []
for item in range(10):
    lista.append(item**2)
print(lista)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [43]:
#Agora reescrevendo o código com list compreenshion
lista = [item**2 for item in range(10)]
print(lista)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Aplicando no nosso problema

In [44]:
#Dic Comprehensions
nome_aprovados = [chave for chave,valor in notas_alunos.items() if valor >=7]
print(nome_aprovados)

['Mauricio', 'Mariana']


### > Aula - 03/02/2021<br>
> Aula: 04 <br>
> Módulo: 00 <br>
> Turma: DSTN01

O objetivo dessa aula é introduzir a biblioteca Numpy.


**Tópicos**:
* Numpy:
 - ndarray
 - Inicialização de Arrays Numpy e Primeiros Passos
 - Manipulação das dimensões de um array
 - Selecioando partes do array




# Numpy (Parte I)

### O que é numpy??

O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos.
Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* Modelos de Machine Learning:
* Processamento de Imagem e Computação Gráfica:
* Tarefas matemáticas: 

### O  ndarry

A estrutura de dados mais importante que o NumPy fornece é um objeto poderoso, um tipo de Array, chamada ndarray.<br>

Esse Array NumPy é uma tabela de elementos (geralmente números), todos do mesmo tipo, indexados por uma tupla de inteiros positivos.<br>

O array do módulo numpy é otimizado para grandes volumes de dados, tem uma estrutura interna compacta e realiza várias operações em paralelo. Além disso, o array numpy suporta tipos de dados não numéricos e é possível fazer operações matemáticas sobre todos os seus valores com apenas uma instrução.<br>

### numpy.array é a função para criar um ndarray

Os principais atributos do ndarray são:
* os tipos de dados (dtype) 
* shape
* size
* ndim

In [45]:
import numpy as np

In [46]:

my_array = np.array(((2,23,55),  #usamos a função array do NumPy para criar uma matriz
                    (5,9,21),
                    (8,4,11),
                    (19,5,4)))
print (my_array)

[[ 2 23 55]
 [ 5  9 21]
 [ 8  4 11]
 [19  5  4]]


In [71]:
# Para saber o tipo de dado da matriz podemos recorrer ao atributo dtype
my_array.dtype

dtype('int32')

In [72]:
# para saber o formato de um array temos o atributo shape. Ele retorna uma tupla contendo o formato do array

my_array.shape

(4, 4)

In [73]:

# O atributo size retorna o número de elementos na matriz.

my_array.size

16

In [75]:
# O atributo ndim retornará o número de dimensões da matriz



my_array.ndim

2

##### Desafio 01 - Gere e mostre a matriz transposta da matriz_inicial: (10 min - pesquisem no google)

In [66]:
matriz_inicial =np.array([[10,    20, 30 ],
                           [3,    50, 5  ],
                           [70,   80, 90 ],
                           [100, 110, 120]])

# Criando uma mariz Transposta:

matriz_inicial.T

array([[ 10,   3,  70, 100],
       [ 20,  50,  80, 110],
       [ 30,   5,  90, 120]])

### Selecionado partes do array

In [52]:
# para selecionar elementos na matriz podemos usar a seguinte sintaxe

print(my_array[0,2])

55


In [53]:
# selecionando apenas a primeira linha

print (my_array[0,:])

[ 2 23 55]


In [64]:
# selecionando apenas a  coluna 2

my_array[:, 2 ]

array([93, 78, 16,  0])

In [82]:
# criando uma matriz preenchida com zeros 

zeros_array = np.zeros([2,3], dtype = int)
zeros_array

array([[0, 0, 0],
       [0, 0, 0]])

## Manipulação das dimensões de um array

Se temos um array de dimensões n x m, podemos aplicar uma reformatação, para que mude suas dimensões sem alterar os dados.
O importante é que o produto n.m seja constante.



Exemplo 4 </n>
n (numeros de linhas) = 4 </n>
m (numero de colunas) = 4 </n>

n x m = 16  </n>
Possibilidades de reformulação:  </n>
    
* 2*8 </n>
* 8*2 </n>
* 1*16 </n>

    


In [83]:


my_array = np.array(((64, 112, 93, 21),
                     (7, 26, 78, 930),
                     (23, 18, 16, 22),
                     (44, 23, 0, 19)))
my_array


array([[ 64, 112,  93,  21],
       [  7,  26,  78, 930],
       [ 23,  18,  16,  22],
       [ 44,  23,   0,  19]])

In [84]:
# função reshape
my_array_reshaped = np.reshape(my_array, (8,2))

my_array_reshaped

array([[ 64, 112],
       [ 93,  21],
       [  7,  26],
       [ 78, 930],
       [ 23,  18],
       [ 16,  22],
       [ 44,  23],
       [  0,  19]])

In [85]:
my_array_reshaped = np.reshape(my_array, (2,8))
my_array_reshaped

array([[ 64, 112,  93,  21,   7,  26,  78, 930],
       [ 23,  18,  16,  22,  44,  23,   0,  19]])

In [86]:
#O comando ravel distorce o array multidimensional e o transforma em um array 1D.
uma_dimensao = my_array_reshaped.ravel()
uma_dimensao

array([ 64, 112,  93,  21,   7,  26,  78, 930,  23,  18,  16,  22,  44,
        23,   0,  19])

In [87]:
# Posso ter uma lista e transformá-la
lista = [1,2,3]
print(type(lista))
# podemos definir o tipo


<class 'list'>


In [61]:
np_array_da_lista = np.array(lista, int) 
print(np_array_da_lista)

[1 2 3]


In [62]:
type(np_array_da_lista)

numpy.ndarray

### Exercício:
Print elemento por elemento (utilizando For loop) o seguinte array: <br>
    array_exercicio = np.arraynp.array([[1,2,3],[4,5,6]])

In [63]:
array_exercicio = np.array([[1,2,3],[4,5,6]])


In [88]:
array_exercicio


array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
for x in array_exercicio:
    for y in x:
        print(y)

1
2
3
4
5
6


In [115]:
for x in np.nditer(array_exercicio):
    print(x)

1
2
3
4
5
6
